# Generated by Django 3.1.5 on 2021-01-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='spinviewer_col_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='object',
            name='spinviewer_row_count',
            field=models.IntegerField(default=0),
        ),
    ]
