# Generated by Django 3.1.5 on 2021-01-12 19:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210112_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, max_length=500, null=True, upload_to='uploads/annnotations/')),
                ('description', models.TextField(max_length=500)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.object')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_index', models.IntegerField(default=0)),
                ('position_x', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('position_y', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.annotation')),
            ],
            options={
                'verbose_name': 'AnnotationPos',
                'verbose_name_plural': 'AnnotationPos',
            },
        ),
        migrations.RemoveField(
            model_name='annnotationpos',
            name='annotation',
        ),
        migrations.DeleteModel(
            name='Annnotation',
        ),
        migrations.DeleteModel(
            name='AnnnotationPos',
        ),
    ]
