# Generated by Django 3.1.5 on 2021-01-19 12:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210112_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotationpos',
            options={'verbose_name': 'AnnotationPos', 'verbose_name_plural': 'AnnotationPoses'},
        ),
        migrations.AlterField(
            model_name='annotation',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='annotationpos',
            name='position_x',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='annotationpos',
            name='position_y',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='PanoAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, max_length=500, null=True, upload_to='uploads/annnotations/')),
                ('description', models.TextField(default='', max_length=500)),
                ('yaw', models.FloatField(default=0)),
                ('pitch', models.FloatField(default=0)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.object')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
