# Generated by Django 3.1.5 on 2021-01-19 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210119_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationpos',
            name='position_x',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='annotationpos',
            name='position_y',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='panoannotation',
            name='pitch',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='panoannotation',
            name='yaw',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
