# Generated by Django 3.1.5 on 2021-01-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210119_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='uuid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
